[package]
name = "simple-agents-napi"
version.workspace = true
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16", features = ["napi4"] }
napi-derive = "2.16"
tokio = { workspace = true }

simple-agents-core = { path = "../simple-agents-core", version.workspace = true }
simple-agents-providers = { path = "../simple-agents-providers", version.workspace = true }
simple-agent-type = { path = "../simple-agent-type", version.workspace = true }
