/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface WorkflowTelemetryConfigNapi {
  enabled?: boolean
  nerdstats?: boolean
  sampleRate?: number
  payloadMode?: string
  retentionDays?: number
  multiTenant?: boolean
  toolTraceMode?: string
}
export interface WorkflowTraceContextNapi {
  traceId?: string
  spanId?: string
  parentSpanId?: string
  traceparent?: string
  tracestate?: string
  baggage?: Record<string, string>
}
export interface WorkflowTraceTenantNapi {
  workspaceId?: string
  userId?: string
  conversationId?: string
  requestId?: string
  runId?: string
}
export interface WorkflowTraceConfigNapi {
  context?: WorkflowTraceContextNapi
  tenant?: WorkflowTraceTenantNapi
}
/**
 * Run options for [`super::WorkflowYamlRunRequest`] and related APIs (no arbitrary top-level keys;
 * matches Rust `YamlWorkflowRunOptions` + `include_events` for request parsing).
 */
export interface WorkflowRunOptionsNapi {
  model?: string
  telemetry?: WorkflowTelemetryConfigNapi
  trace?: WorkflowTraceConfigNapi
  includeEvents?: boolean
}
export interface WorkflowYamlRunFlags {
  healing: boolean
  workflowStreaming: boolean
  nodeLlmStreaming: boolean
}
export interface ParsedWorkflowYamlExecutionRequest {
  workflowPath: string
  workflowInput: Record<string, unknown>
  healing: boolean
  workflowStreaming: boolean
  nodeLlmStreaming: boolean
  workflowOptions: Record<string, unknown>
}
export interface WorkflowYamlRunRequest {
  workflowPath: string
  messages: Array<MessageInput>
  healing: boolean
  workflowStreaming: boolean
  nodeLlmStreaming: boolean
  splitStreamDeltas?: boolean
  extraWorkflowInput?: Record<string, unknown>
  workflowOptions?: WorkflowRunOptionsNapi
}
export interface CompleteOptions {
  maxTokens?: number
  temperature?: number
  topP?: number
  stream?: boolean
  /** "standard" | "healed_json" | "schema" */
  mode?: string
  schema?: unknown
}
export interface ContentPartInput {
  type: 'text' | 'image' | 'audio' | 'video'
  text?: string
  mediaType?: string
  data?: string
}
export interface MessageInput {
  role: 'system' | 'user' | 'assistant' | 'tool'
  content: string | Array<ContentPartInput>
  name?: string
  toolCallId?: string
  toolCalls?: Array<JsToolCall>
}
export interface JsToolCallFunction {
  name: string
  arguments: string
}
export interface ToolCallResultFunction {
  name: string
  arguments: string
}
export interface ToolCallResult {
  id: string
  toolType: string
  function: ToolCallResultFunction
}
export interface JsToolCall {
  id: string
  toolType: string
  function: JsToolCallFunction
}
export interface CompletionUsage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
}
export interface HealingData {
  value?: unknown
  flags: Array<string>
  confidence: number
}
export interface CompletionResult {
  id: string
  model: string
  role: string
  content?: string
  toolCalls?: Array<ToolCallResult>
  finishReason?: string
  usage: CompletionUsage
  usageAvailable: boolean
  latencyMs: number
  raw?: string
  healed?: HealingData
  coerced?: HealingData
}
export interface StreamChunk {
  id: string
  model: string
  content?: string
  finishReason?: string
  error?: string
  raw?: string
}
export interface StreamDelta {
  id: string
  model: string
  index: number
  role?: string
  content?: string
  finishReason?: string
  raw?: string
}
export interface StreamErrorEvent {
  message: string
}
export interface StreamEvent {
  eventType: string
  delta?: StreamDelta
  error?: StreamErrorEvent
}
export declare function parseWorkflowYamlExecutionRequest(workflowPath: string, messages: Array<MessageInput>, flags: WorkflowYamlRunFlags, extraWorkflowInput?: Record<string, unknown>, workflowOptions?: WorkflowRunOptionsNapi): ParsedWorkflowYamlExecutionRequest
export class Client {
  /**
   * Create a client from an API key.
   *
   * Uses `OpenAiCompatProvider` under the hood; pass `baseUrl` to override
   * the endpoint.
   */
  constructor(apiKey: string, baseUrl?: string | undefined | null)
  /** Create a client using environment variables for the API key. */
  static fromEnv(): Client
  complete(model: string, promptOrMessages: string | MessageInput[], options?: CompleteOptions): Promise<CompletionResult>
  streamComplete(model: string, promptOrMessages: string | MessageInput[], onChunk: (chunk: StreamChunk) => void, options?: CompleteOptions): Promise<CompletionResult>
  runWorkflow(workflowPath: string, workflowInput: { messages?: MessageInput[]; [key: string]: unknown }, workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown>; include_events?: boolean }, customWorkerDispatch?: (req: { handler: string; handlerFile?: string; payload: unknown; context: unknown }) => unknown): Record<string, unknown>
  streamWorkflow(workflowPath: string, workflowInput: { messages?: MessageInput[]; [key: string]: unknown }, onEvent: (err: unknown, eventJson: string) => void, workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown>; include_events?: boolean }, customWorkerDispatch?: (req: { handler: string; handlerFile?: string; payload: unknown; context: unknown }) => unknown): Promise<Record<string, unknown>>
  /**
   * Run a YAML workflow (new unified API).
   *
   * ```ts
   * const result = await client.run("workflow.yaml", messages);
   * const result = await client.run("workflow.yaml", messages, { tools: myTools });
   * ```
   */
  run(workflowPath: string, messages: MessageInput[], opts?: { tools?: unknown; workflowOptions?: Record<string, unknown>; customWorker?: (req: { handler: string; handlerFile?: string; payload: unknown; context: unknown }) => unknown }): Record<string, unknown>
  /**
   * Stream a YAML workflow (new unified API).
   *
   * ```ts
   * const result = await client.stream("workflow.yaml", messages, onEvent);
   * ```
   */
  stream(workflowPath: string, messages: MessageInput[], onEvent?: (err: unknown, eventJson: string) => void, opts?: { tools?: unknown; workflowOptions?: Record<string, unknown>; customWorker?: (req: { handler: string; handlerFile?: string; payload: unknown; context: unknown }) => unknown }): Promise<Record<string, unknown>>
  /**
   * Resume a workflow from a checkpoint (new unified API).
   *
   * ```ts
   * const result = await client.resume(checkpoint);
   * ```
   */
  resume(checkpoint: Record<string, unknown>, opts?: { workflowOptions?: Record<string, unknown>; customWorker?: (req: { handler: string; handlerFile?: string; payload: unknown; context: unknown }) => unknown }): Record<string, unknown>
}
