/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface WorkflowTelemetryConfigNapi {
  enabled?: boolean
  nerdstats?: boolean
  sampleRate?: number
  payloadMode?: string
  retentionDays?: number
  multiTenant?: boolean
  toolTraceMode?: string
}
export interface WorkflowTraceContextNapi {
  traceId?: string
  spanId?: string
  parentSpanId?: string
  traceparent?: string
  tracestate?: string
  baggage?: Record<string, string>
}
export interface WorkflowTraceTenantNapi {
  workspaceId?: string
  userId?: string
  conversationId?: string
  requestId?: string
  runId?: string
}
export interface WorkflowTraceConfigNapi {
  context?: WorkflowTraceContextNapi
  tenant?: WorkflowTraceTenantNapi
}
/**
 * Run options for [`super::WorkflowYamlRunRequest`] and related APIs (no arbitrary top-level keys;
 * matches Rust `YamlWorkflowRunOptions` + `include_events` for request parsing).
 */
export interface WorkflowRunOptionsNapi {
  model?: string
  telemetry?: WorkflowTelemetryConfigNapi
  trace?: WorkflowTraceConfigNapi
  includeEvents?: boolean
}
export interface WorkflowYamlRunFlags {
  healing: boolean
  workflowStreaming: boolean
  nodeLlmStreaming: boolean
}
export interface ParsedWorkflowYamlExecutionRequest {
  workflowPath: string
  workflowInput: Record<string, unknown>
  healing: boolean
  workflowStreaming: boolean
  nodeLlmStreaming: boolean
  workflowOptions: Record<string, unknown>
}
export interface WorkflowYamlRunRequest {
  workflowPath: string
  messages: Array<MessageInput>
  healing?: boolean
  workflowStreaming?: boolean
  nodeLlmStreaming?: boolean
  splitStreamDeltas?: boolean
  debugStreamParse?: boolean
  extraWorkflowInput?: Record<string, unknown>
  workflowOptions?: WorkflowRunOptionsNapi
}
export interface ClientOptions {
  timeoutSeconds?: number
  retryAttempts?: number
  /** "none" | "fixed" | "exponential" */
  retryStrategy?: string
}
export type ReasoningEffort = 'none' | 'min' | 'low' | 'medium' | 'high' | 'xhigh' | 'max' | number
export interface CompleteOptions {
  maxTokens?: number
  temperature?: number
  topP?: number
  stream?: boolean
  /** "standard" | "healed_json" | "schema" */
  mode?: string
  schema?: unknown
  sendSchema?: boolean
  reasoningEffort?: ReasoningEffort
}
export interface ContentPartInput {
  type: 'text' | 'image' | 'audio' | 'video'
  text?: string
  mediaType?: string
  data?: string
}
export interface MessageInput {
  role: 'system' | 'user' | 'assistant' | 'tool'
  content: string | Array<ContentPartInput>
  name?: string
  toolCallId?: string
  toolCalls?: Array<JsToolCall>
}
export interface JsToolCallFunction {
  name: string
  arguments: string
}
export interface ToolCallResultFunction {
  name: string
  arguments: string
}
export interface ToolCallResult {
  id: string
  toolType: string
  function: ToolCallResultFunction
}
export interface JsToolCall {
  id: string
  toolType: string
  function: JsToolCallFunction
}
export interface CompletionUsage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
}
export interface HealingData {
  value?: unknown
  flags: Array<string>
  confidence: number
  error?: string
}
export interface CompletionResult {
  id: string
  model: string
  role: string
  content?: string
  toolCalls?: Array<ToolCallResult>
  finishReason?: string
  usage: CompletionUsage
  usageAvailable: boolean
  latencyMs: number
  raw?: string
  healed?: HealingData
  coerced?: HealingData
}
export interface StreamChunk {
  id: string
  model: string
  content?: string
  finishReason?: string
  snapshot?: unknown
  snapshotConfidence?: number
  coercedSnapshot?: unknown
  coercedConfidence?: number
  isComplete?: boolean
  error?: string
  raw?: string
}
export declare function parseWorkflowYamlExecutionRequest(workflowPath: string, messages: Array<MessageInput>, flags: WorkflowYamlRunFlags, extraWorkflowInput?: Record<string, unknown>, workflowOptions?: WorkflowRunOptionsNapi): ParsedWorkflowYamlExecutionRequest
/**
 * Copies OTLP-related variables into the Rust process environment (`std::env`).
 *
 * Bun and some Node setups update `process.env` in JavaScript without updating the
 * OS environment that `std::env::var` reads in native code. Call this after setting
 * `SIMPLE_AGENTS_TRACING_ENABLED` / `OTEL_EXPORTER_OTLP_*` in JS and **before** the
 * first workflow run so workflow tracing initializes with OTLP enabled.
 */
export declare function syncOtelEnvFromProcess(tracingEnabled: string, otlpProtocol: string, otlpEndpoint: string, otlpHeaders: string, otelServiceName?: string | undefined | null): void
export class Client {
  /**
   * Create a client from an API key.
   *
   * Uses `OpenAiCompatProvider` under the hood; pass `baseUrl` to override
   * the endpoint.
   */
  constructor(apiKey: string, baseUrl?: string | undefined | null, options?: ClientOptions | undefined | null)
  /** Create a client using environment variables for the API key. */
  static fromEnv(options?: ClientOptions | undefined | null): Client
  complete(model: string, promptOrMessages: string | MessageInput[], options?: CompleteOptions): Promise<CompletionResult>
  streamComplete(model: string, promptOrMessages: string | MessageInput[], onChunk: (chunk: StreamChunk) => void, options?: CompleteOptions): Promise<CompletionResult>
  runWorkflow(workflowPath: string, workflowInput: { messages?: MessageInput[]; [key: string]: unknown }, workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown>; include_events?: boolean }, workflowExecution?: { healing?: boolean; workflowStreaming?: boolean; nodeLlmStreaming?: boolean; splitStreamDeltas?: boolean; debugStreamParse?: boolean }, resume?: Record<string, unknown>, humanResponse?: unknown, customWorkerDispatch?: (req: { handler: string; handlerFile?: string; payload: unknown; context: unknown }) => unknown): Record<string, unknown> | Promise<Record<string, unknown>>
  streamWorkflow(workflowPath: string, workflowInput: { messages?: MessageInput[]; [key: string]: unknown }, onEvent: (eventJson: string) => void, workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown>; include_events?: boolean }, workflowExecution?: { healing?: boolean; workflowStreaming?: boolean; nodeLlmStreaming?: boolean; splitStreamDeltas?: boolean; debugStreamParse?: boolean }, resume?: Record<string, unknown>, humanResponse?: unknown, customWorkerDispatch?: (req: { handler: string; handlerFile?: string; payload: unknown; context: unknown }) => unknown): Promise<Record<string, unknown>>
}

// --- simple-agents wrapper API additions ---

export interface EvalSuiteRequest {
  workflowPath: string
  datasetPath: string
  evaluator: EvalEvaluator
  suiteId?: string
  execution?: { healing?: boolean; workflowStreaming?: boolean; nodeLlmStreaming?: boolean; splitStreamDeltas?: boolean }
  workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown>; include_events?: boolean }
  customWorkerDispatch?: (req: { handler: string; handlerFile?: string; payload: unknown; context: unknown }) => unknown
}

export interface EvalDatasetRecord {
  id: string
  input: Record<string, unknown>
  expected_output: Record<string, unknown>
  rubric?: unknown
  custom?: unknown
  metadata?: unknown
}

export interface EvalCase {
  id: string
  input: Record<string, unknown>
  expectedOutput: Record<string, unknown>
  actualOutput: Record<string, unknown>
  record: EvalDatasetRecord
}

export type EvalEvaluator = (case_: EvalCase) => EvalResult | boolean | Promise<EvalResult | boolean>

export interface EvalSummary {
  totalCases: number
  passedCases: number
  failedCases: number
  errorCases: number
  passRate: number
}

export interface EvalErrorInfo {
  code: string
  message: string
}

export interface EvalCaseResult {
  caseId: string
  status: 'passed' | 'failed' | 'error'
  expected?: unknown
  actual?: unknown
  evaluations?: Array<EvalResult>
  workflowOutput?: Record<string, unknown>
  error?: EvalErrorInfo
}

export interface EvalResult {
  id: string
  status: 'passed' | 'failed' | 'error'
  passed: boolean
  score?: number
  expected?: unknown
  actual?: unknown
  reason?: string
  metadata?: unknown
}

export interface EvalReport {
  suiteId: string
  status: 'passed' | 'failed' | 'error'
  summary: EvalSummary
  cases: Array<EvalCaseResult>
}

export interface WorkflowYamlRunRequest {
  customWorkerDispatch?: (req: { handler: string; handlerFile?: string; payload: unknown; context: unknown }) => unknown
}

export interface Client {
  runEvalSuite(request: EvalSuiteRequest): Promise<EvalReport>
  run(request: WorkflowYamlRunRequest): Record<string, unknown> | Promise<Record<string, unknown>>
  stream(request: WorkflowYamlRunRequest, onEvent: (eventJson: string) => void): Promise<Record<string, unknown>>
}
