/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CompleteOptions {
  maxTokens?: number
  temperature?: number
  topP?: number
  stream?: boolean
  /** "standard" | "healed_json" | "schema" */
  mode?: string
  schema?: unknown
}
export interface MessageInput {
  role: 'system' | 'user' | 'assistant' | 'tool'
  content: string
  name?: string
  toolCallId?: string
  toolCalls?: Array<JsToolCall>
}
export interface JsToolCallFunction {
  name: string
  arguments: string
}
export interface ToolCallResultFunction {
  name: string
  arguments: string
}
export interface ToolCallResult {
  id: string
  toolType: string
  function: ToolCallResultFunction
}
export interface JsToolCall {
  id: string
  toolType: string
  function: JsToolCallFunction
}
export interface CompletionUsage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
}
export interface HealingData {
  value?: unknown
  flags: Array<string>
  confidence: number
}
export interface CompletionResult {
  id: string
  model: string
  role: string
  content?: string
  toolCalls?: Array<ToolCallResult>
  finishReason?: string
  usage: CompletionUsage
  usageAvailable: boolean
  latencyMs: number
  raw?: string
  healed?: HealingData
  coerced?: HealingData
}
export interface StreamChunk {
  id: string
  model: string
  content?: string
  finishReason?: string
  error?: string
  raw?: string
}
export interface StreamDelta {
  id: string
  model: string
  index: number
  role?: string
  content?: string
  finishReason?: string
  raw?: string
}
export interface StreamErrorEvent {
  message: string
}
export interface StreamEvent {
  eventType: string
  delta?: StreamDelta
  error?: StreamErrorEvent
}
export declare class Client {
  constructor(provider: string)
  complete(model: string, promptOrMessages: string | MessageInput[], options?: CompleteOptions): Promise<unknown>
  stream(model: string, promptOrMessages: string | MessageInput[], onChunk: (chunk: StreamChunk) => void, options?: CompleteOptions): Promise<unknown>
  streamEvents(model: string, promptOrMessages: string | MessageInput[], onEvent: (event: StreamEvent) => void, options?: CompleteOptions): Promise<unknown>
  runEmailWorkflowYaml(workflowPath: string, emailText: string): any
  runWorkflowYaml(workflowPath: string, workflowInput: { email_text?: string; messages?: MessageInput[]; [key: string]: unknown }): any
  runWorkflowYamlWithEvents(workflowPath: string, workflowInput: { email_text?: string; messages?: MessageInput[]; [key: string]: unknown }, workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown> }): any
  runEmailWorkflowYamlWithEvents(workflowPath: string, emailText: string, workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown> }): any
  runWorkflowYamlStream(workflowPath: string, workflowInput: { email_text?: string; messages?: MessageInput[]; [key: string]: unknown }, onEvent: (err: unknown, eventJson: string) => void, workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown> }): Promise<any>
  runEmailWorkflowYamlStream(workflowPath: string, emailText: string, onEvent: (err: unknown, eventJson: string) => void, workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown> }): Promise<any>
  runWorkflowYamlWithOptions(workflowPath: string, workflowInput: { email_text?: string; messages?: MessageInput[]; [key: string]: unknown }, workflowOptions?: { telemetry?: Record<string, unknown>; trace?: Record<string, unknown> }): any
}
