[package]
name = "simple-agents-examples"
version.workspace = true
edition = "2021"

[package.metadata.simpleagents.dependency-policy]
minimum-release-age = "182 days"

[dev-dependencies]
dotenv = "=0.15.0"
futures-util = { workspace = true }
serde_json = { workspace = true }
simple-agents-core = { path = "../crates/simple-agents-core" }
simple-agents-healing = { workspace = true }
simple-agents-providers = { workspace = true }
simple-agents-workflow = { path = "../crates/simple-agents-workflow" }
simple-agent-type = { workspace = true }
tokio = { workspace = true }

[[example]]
name = "full_api_example"
path = "full_api_example.rs"

[[example]]
name = "jaro_scores"
path = "jaro_scores.rs"

[[example]]
name = "workflow_chat_history_rust"
path = "workflow_chat_history_rust.rs"
