[project]
name = "python-test-simpleagents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "simple-agents-py[pydantic]",
    "python-dotenv==1.2.1",
    "fastapi==0.135.3",
    "uvicorn[standard]==0.44.0",
    "openai==2.30.0",
]

[tool.simpleagents.dependency-policy]
minimum-release-age = "182 days"
