[package]
name = "simple-agents-py"
version.workspace = true
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "simple_agents_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module", "abi3-py312", "serde"] }
tokio = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }

simple-agents-core = { path = "../simple-agents-core", version = "0.1.0" }
simple-agents-providers = { path = "../simple-agents-providers", version = "0.1.0" }
simple-agent-type = { path = "../simple-agent-type", version = "0.1.0" }
