[package]
name = "simple-agents-py"
version = "0.1.3"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "simple_agents_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module", "abi3-py312"] }
tokio = { workspace = true }
reqwest = { workspace = true }

simple-agents-core = { path = "../simple-agents-core" }
simple-agents-providers = { path = "../simple-agents-providers" }
simple-agent-type = { path = "../simple-agent-type" }
