[package]
name = "simple-agents-ffi"
version.workspace = true
edition = "2021"
authors = ["SimpleAgents Contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rishub/simple-agents"
homepage = "https://github.com/rishub/simple-agents"
documentation = "https://docs.rs/simple-agent-type"
description = "C-compatible FFI bindings for SimpleAgents"
readme = "README.md"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }

simple-agents-core = { path = "../simple-agents-core", version.workspace = true }
simple-agents-providers = { path = "../simple-agents-providers", version.workspace = true }
simple-agent-type = { path = "../simple-agent-type", version.workspace = true }
