[package]
name = "simple-agents-ffi"
version.workspace = true
edition = "2021"
authors = ["SimpleAgents Contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/CraftsMan-Labs/SimpleAgents"
homepage = "https://github.com/CraftsMan-Labs/SimpleAgents"
documentation = "https://docs.rs/simple-agent-type"
description = "C-compatible FFI bindings for SimpleAgents"
readme = "README.md"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }

simple-agents-core = { path = "../simple-agents-core", version = "0.3.1" }
simple-agents-providers = { path = "../simple-agents-providers", version = "0.3.1" }
simple-agents-workflow = { path = "../simple-agents-workflow", version = "0.3.1" }
simple-agent-type = { workspace = true }
